### ISSUE TITLE
How many epochs do you let it run for normally?

### ISSUE THREAD

**Issue by increpare** [loovjo/ilo-pi-ante-toki#1]
This is super cool :) I'm just playing around with it now.  

One question: how many epochs do you let it train for normally?

**Comment by xeniagda** [comment]
Hi! The algorithm usually runs for a few hundred epochs at least, the current instance at https://coral.shoes/ilo/ has run for a few thousand I think. Unfortunately I don't log the training progress, so the numbers are only estimates :(

**Comment by increpare** [comment]
Ah cool, good to know the ballpark. 

[ The Toki Pona corpus on tatoeba has been getting some love the last few months to improve the quality of translations.  It's still ongoing, but it might be of interest to compare performance once that settles down. ]

(also, consider linking to the instance in the readme. :) )
