### ISSUE TITLE
Release the trained model?

### ISSUE THREAD

**Issue by Devetec** [loovjo/ilo-pi-ante-toki#3]
It would be nice to have the model for use locally.

**Comment by xeniagda** [comment]
Hi, sorry for taking a while, but the save files are now available at `https://kijetesantaka.lu/save/<file>.pth`. The following files are available: `save/dec-aux.pth, save/dec-sec.pth, save/enc.pth, save/opt-aux.pth, save/opt-sec.pth`. The `opt-`-files are data for the optimizers, if you do not want to train the AI yourself but only used the trained model they are cessary.
